<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
		<PublishReadyToRun>false</PublishReadyToRun>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="app.ico">
			<LogicalName>app.ico</LogicalName>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DnsClient" Version="1.8.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Strings.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Strings.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Strings.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Strings.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Strings.zh-TW.resx">
			<Generator></Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Strings.zh-CN.resx">
			<Generator></Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Strings.ja.resx">
			<Generator></Generator>
		</EmbeddedResource>
	</ItemGroup>
</Project>