//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinToolBridge.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinToolBridge.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge is already running in the background! 的當地語系化字串。
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge 的當地語系化字串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Double-click tray icon or click here to view console. 的當地語系化字串。
        /// </summary>
        internal static string BalloonReadyText {
            get {
                return ResourceManager.GetString("BalloonReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge Ready 的當地語系化字串。
        /// </summary>
        internal static string BalloonReadyTitle {
            get {
                return ResourceManager.GetString("BalloonReadyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Connected] Frontend client connected ({0}) 的當地語系化字串。
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Disconnected] Client offline ({0}) 的當地語系化字串。
        /// </summary>
        internal static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Connection Error] {0} 的當地語系化字串。
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge Started 的當地語系化字串。
        /// </summary>
        internal static string ConsoleStarted {
            get {
                return ResourceManager.GetString("ConsoleStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge Debug Console (v{0}) 的當地語系化字串。
        /// </summary>
        internal static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit WinToolBridge 的當地語系化字串。
        /// </summary>
        internal static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Handshake] From {0} {1} (Client protocol: v{2} ~ v{3}) 的當地語系化字串。
        /// </summary>
        internal static string HandshakeReceived {
            get {
                return ResourceManager.GetString("HandshakeReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port: {0} 的當地語系化字串。
        /// </summary>
        internal static string PortDisplay {
            get {
                return ResourceManager.GetString("PortDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to start bridge server (Port {0}): {1} 的當地語系化字串。
        /// </summary>
        internal static string PortStartFailed {
            get {
                return ResourceManager.GetString("PortStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Retry] DAT [{0}] ACK timeout, retransmitting (Attempt #{1})... 的當地語系化字串。
        /// </summary>
        internal static string RetryingSend {
            get {
                return ResourceManager.GetString("RetryingSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server started, listening on 127.0.0.1:{0} (Protocol: v{1}) 的當地語系化字串。
        /// </summary>
        internal static string ServerListening {
            get {
                return ResourceManager.GetString("ServerListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Stop Error] {0} 的當地語系化字串。
        /// </summary>
        internal static string ServerStopError {
            get {
                return ResourceManager.GetString("ServerStopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Server listener stopped 的當地語系化字串。
        /// </summary>
        internal static string ServerStopped {
            get {
                return ResourceManager.GetString("ServerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start with Windows 的當地語系化字串。
        /// </summary>
        internal static string StartOnBoot {
            get {
                return ResourceManager.GetString("StartOnBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status: Running (v{0}) 的當地語系化字串。
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinToolBridge v{0}
        ///(Double-click to open debug console) 的當地語系化字串。
        /// </summary>
        internal static string TrayTip {
            get {
                return ResourceManager.GetString("TrayTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [Incompatible Version] Local: v{0}, Requested: v{1} ~ v{2} 的當地語系化字串。
        /// </summary>
        internal static string VersionIncompatible {
            get {
                return ResourceManager.GetString("VersionIncompatible", resourceCulture);
            }
        }
    }
}
